[package]
name = "aa-bundler-examples"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
description = """
AA (ERC-4337) Bundler examples
"""

[dev-dependencies]
aa-bundler-primitives = { path = "../crates/primitives" }

anyhow = "1"
ethers = { version = "2.0.4" }
tokio = { workspace = true }

[[example]]
name = "user-operation"
path = "user_operation.rs"

[dependencies]
jsonrpsee = { version = "0.18.2", features = ["http-client", "server"] }
serde_json = { version = "1" }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.3" }

