[package]
name = "aa-bundler-rpc"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler RPC implementation
"""

[dependencies]
aa-bundler-grpc = { path = "../grpc" }
aa-bundler-primitives = { path = "../primitives" }

anyhow = "1"
async-trait = "0.1"
ethers = { workspace = true }
git-version = "0.3.5"
hyper = { version = "0.14" }
jsonrpsee = { version = "0.18.2", features = ["server", "macros", "client"] }
serde = "1"
serde_json = "1"
tonic = { version = "0.8", default-features = false, features = ["transport"] }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.1", features = ["cors"] }
