[package]
name = "aa-bundler"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler
"""
default-run = "bundler"

[dependencies]
aa-bundler-grpc = { path = "../../crates/grpc" }
aa-bundler-primitives = { path = "../../crates/primitives" }
aa-bundler-rpc = { path = "../../crates/rpc" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "4.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
ethers = { workspace = true }
expanded-pathbuf = "0.1"
log = "0.4.19"
pin-utils = "0.1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bundler.rs"
name = "bundler"

[[bin]]
path = "src/bundler-uopool.rs"
name = "bundler-uopool"

[[bin]]
path = "src/bundler-rpc.rs"
name = "bundler-rpc"

[[bin]]
path = "src/create-wallet.rs"
name = "create-wallet"

[[bin]]
path = "src/quick-bundler.rs"
name = "quick-bundler"
