[package]
name = "silius"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) bundler - Silius
"""
default-run = "silius"

[dependencies]

anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "4.0"
ethers = { workspace = true }
expanded-pathbuf = "0.1"
log = "0.4.19"
pin-utils = "0.1"
silius-bundler = { path = "../../crates/bundler" }
silius-grpc = { path = "../../crates/grpc" }
silius-primitives = { path = "../../crates/primitives" }
silius-rpc = { path = "../../crates/rpc" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/silius.rs"
name = "silius"

[[bin]]
path = "src/silius-uopool.rs"
name = "silius-uopool"

[[bin]]
path = "src/silius-rpc.rs"
name = "silius-rpc"

[[bin]]
path = "src/create-wallet.rs"
name = "create-wallet"
