[package]
name = "aa-bundler-bundler"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler bundling implementation
"""

[dependencies]
aa-bundler-contracts = { path = "../contracts" }
aa-bundler-primitives = { path = "../primitives" }
alloy-primitives = "0.3.0"
alloy-sol-types = "0.3.0"
anyhow = "1"

async-trait = "0.1"
bytes = "1.4.0"
dotenv = "0.15.0"
ethers = { workspace = true, features = ["abigen-online"] }
ethers-flashbots = { git = "https://github.com/da-bao-jian/ethers-flashbots.git", branch = "master" }
jsonrpsee = { version = "0.18.2", features = ["server", "macros", "client"] }
serde = "1"
serde_json = "1"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.4.0"


