[package]
name = "aa-bundler-bundler"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) Bundler bundling implementation
"""

[dependencies]
aa-bundler-contracts = { path = "../contracts" }
aa-bundler-primitives = { path = "../primitives" }

anyhow = "1"
ethers = { workspace = true }
tracing = { workspace = true }
ethers-flashbots = "0.13.1"
url = "2.4.0"
tokio.workspace = true
