on:
  push:
    branches:
      - main

name: Create and publish a Docker image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git Tag
        run: echo "tags=$(git describe --tags)" >> $GITHUB_OUTPUT
        id: tag

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Fetch third-party dependencies
        run: |
          make fetch-thirdparty
  
      - name: Setup Yarn cache - submodule "thirdparty/account-abstraction"
        uses: actions/setup-node@v3
        with:
          node-version: '16.17'
          cache: 'yarn'
          cache-dependency-path: crates/contracts/thirdparty/account-abstraction
  
      - name: Setup Yarn cache - submodule "thirdparty/bundler"
        uses: actions/setup-node@v3
        with:
          node-version: '16.17'
          cache: 'yarn'
          cache-dependency-path: tests/thirdparty/bundler
        
      - name: Setup third-party dependencies
        run: |
          make setup-thirdparty

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
